### ISSUE TITLE
Feedback for “Selector Layer: Extra Queries”

### ISSUE THREAD

**Issue by dancojocari** [lukethacoder/fflib.dev#2]
There is a typo in the code. 

Instead of 

`@TestVisible`
`  private String getExtraQueries(Boolean removeFirstAnd) {`
`    String extraQueries =` **s**etFilterIsActive();
`    return removeFirstAnd ? extraQueries.replaceFirst('AND', ' ') : extraQueries;`
`  }`

it should be 

`@TestVisible`
`  private String getExtraQueries(Boolean removeFirstAnd) {`
`    String extraQueries =` **g**etFilterIsActive();
`    return removeFirstAnd ? extraQueries.replaceFirst('AND', ' ') : extraQueries;`
`  }`

**Comment by lukethacoder** [comment]
thanks for flagging this. fixed
